export type ShopItemKind = "badge" | "gem_bundle" | "boost";

export type ShopCatalogItem = {
  id: string;
  kind: ShopItemKind;
  title: string;
  description: string;
  priceGems: number;
  /** XP cost for gem bundles (exchange). */
  priceXp?: number;
  gemsGranted?: number;
  tier: 1 | 2 | 3 | 4 | 5;
  emoji: string;
  /** Iconify id override, e.g. game-icons:laurel-crown */
  icon?: string;
  accent: string;
  featured?: boolean;
};

export const SHOP_CATALOG: ShopCatalogItem[] = [
  {
    id: "badge-streak-spark",
    kind: "badge",
    title: "Streak Spark",
    description: "Profile flair for learners on a hot streak.",
    priceGems: 45,
    tier: 1,
    emoji: "🔥",
    accent: "#f97316",
  },
  {
    id: "badge-hola-hero",
    kind: "badge",
    title: "Hola Hero",
    description: "Celebrate your first greetings mission wins.",
    priceGems: 55,
    tier: 1,
    emoji: "👋",
    accent: "#1cb0f6",
  },
  {
    id: "badge-quiz-star",
    kind: "badge",
    title: "Quiz Star",
    description: "Show off high scores from boss quizzes.",
    priceGems: 75,
    tier: 2,
    emoji: "⭐",
    accent: "#f5c518",
    featured: true,
  },
  {
    id: "badge-path-pioneer",
    kind: "badge",
    title: "Path Pioneer",
    description: "Unlocked for explorers who finish whole units.",
    priceGems: 90,
    tier: 2,
    emoji: "🧭",
    accent: "#58cc02",
  },
  {
    id: "badge-gem-hunter",
    kind: "badge",
    title: "Gem Hunter",
    description: "For collectors who never miss a quest reward.",
    priceGems: 110,
    tier: 3,
    emoji: "💎",
    accent: "#7c3aed",
  },
  {
    id: "badge-maya-crew",
    kind: "badge",
    title: "Maya's Crew",
    description: "Squad badge inspired by the Allen sisters.",
    priceGems: 120,
    tier: 3,
    emoji: "💜",
    accent: "#e8357a",
    featured: true,
  },
  {
    id: "badge-spark-buddy",
    kind: "badge",
    title: "Spark Buddy",
    description: "Robot guide companion flair for your profile.",
    priceGems: 140,
    tier: 4,
    emoji: "🤖",
    accent: "#0ea5e9",
  },
  {
    id: "badge-legend-crown",
    kind: "badge",
    title: "Legend Crown",
    description: "Top-tier badge for mastery across sections.",
    priceGems: 200,
    tier: 5,
    emoji: "👑",
    accent: "#ca8a04",
  },
  {
    id: "badge-butterfly-charm",
    kind: "badge",
    title: "Butterfly Charm",
    description: "Delicate wing relic from the sisters' garden quests.",
    priceGems: 50,
    tier: 1,
    emoji: "🦋",
    accent: "#ec4899",
  },
  {
    id: "badge-ruby-flame",
    kind: "badge",
    title: "Ruby Flame",
    description: "A burning stone for learners who never cool off.",
    priceGems: 60,
    tier: 2,
    emoji: "🔴",
    accent: "#ef4444",
  },
  {
    id: "badge-crystal-orb",
    kind: "badge",
    title: "Crystal Orb",
    description: "Scrying stone for curious explorers.",
    priceGems: 70,
    tier: 2,
    emoji: "🔮",
    accent: "#a78bfa",
  },
  {
    id: "badge-star-medal",
    kind: "badge",
    title: "Star Medal",
    description: "Polished medal for consistent classroom stars.",
    priceGems: 80,
    tier: 2,
    emoji: "🌟",
    accent: "#fbbf24",
  },
  {
    id: "badge-scholar-scroll",
    kind: "badge",
    title: "Scholar Scroll",
    description: "Ancient parchment flair for vocabulary masters.",
    priceGems: 88,
    tier: 2,
    emoji: "📜",
    accent: "#92400e",
  },
  {
    id: "badge-suncrest",
    kind: "badge",
    title: "Sun Crest",
    description: "Radiant sun seal for bright morning streaks.",
    priceGems: 85,
    tier: 2,
    emoji: "☀️",
    accent: "#fb923c",
  },
  {
    id: "badge-pearl-tide",
    kind: "badge",
    title: "Pearl Tide",
    description: "Ocean pearl necklace from coastal missions.",
    priceGems: 92,
    tier: 2,
    emoji: "🐚",
    accent: "#38bdf8",
  },
  {
    id: "badge-gold-trophy",
    kind: "badge",
    title: "Gold Trophy",
    description: "Heavy trophy for podium quiz finishes.",
    priceGems: 95,
    tier: 3,
    emoji: "🏆",
    accent: "#eab308",
    featured: true,
  },
  {
    id: "badge-moonstone",
    kind: "badge",
    title: "Moonstone",
    description: "Pale lunar gem for night-owl study sessions.",
    priceGems: 105,
    tier: 3,
    emoji: "🌙",
    accent: "#818cf8",
  },
  {
    id: "badge-forest-wreath",
    kind: "badge",
    title: "Forest Wreath",
    description: "Vine crown from woodland adventure units.",
    priceGems: 108,
    tier: 3,
    emoji: "🌿",
    accent: "#22c55e",
  },
  {
    id: "badge-treasure-map",
    kind: "badge",
    title: "Treasure Map",
    description: "Cartographer relic for map-reading champions.",
    priceGems: 115,
    tier: 3,
    emoji: "🗺️",
    accent: "#d97706",
  },
  {
    id: "badge-wizard-elixir",
    kind: "badge",
    title: "Wizard Elixir",
    description: "Bottled magic for potion-lab game winners.",
    priceGems: 150,
    tier: 4,
    emoji: "🧪",
    accent: "#8b5cf6",
  },
  {
    id: "badge-dragon-scale",
    kind: "badge",
    title: "Dragon Scale",
    description: "Forged scale from legendary boss battles.",
    priceGems: 155,
    tier: 4,
    emoji: "🐉",
    accent: "#dc2626",
  },
  {
    id: "badge-unicorn-relic",
    kind: "badge",
    title: "Unicorn Relic",
    description: "Mythic horn charm for rare perfect runs.",
    priceGems: 165,
    tier: 4,
    emoji: "🦄",
    accent: "#f472b6",
  },
  {
    id: "badge-castle-keeper",
    kind: "badge",
    title: "Castle Keeper",
    description: "Stone keep sigil for section completionists.",
    priceGems: 185,
    tier: 5,
    emoji: "🏰",
    accent: "#64748b",
  },
  {
    id: "badge-rainbow-star",
    kind: "badge",
    title: "Rainbow Star",
    description: "Prismatic star for all-around adventurers.",
    priceGems: 195,
    tier: 5,
    emoji: "🌈",
    accent: "#e879f9",
    featured: true,
  },
  {
    id: "badge-stone-sigil",
    kind: "badge",
    title: "Stone Sigil",
    description: "Carved rune block from the relic quarry.",
    priceGems: 72,
    tier: 2,
    emoji: "🪨",
    accent: "#78716c",
  },
  {
    id: "badge-gem-chain",
    kind: "badge",
    title: "Gem Chain",
    description: "Linked jewels for dedicated collectors.",
    priceGems: 125,
    tier: 3,
    emoji: "📿",
    accent: "#06b6d4",
  },
  {
    id: "badge-energy-blade",
    kind: "badge",
    title: "Energy Blade",
    description: "Glowing sword flair for combat quiz modes.",
    priceGems: 175,
    tier: 4,
    emoji: "⚔️",
    accent: "#3b82f6",
  },
  {
    id: "badge-wizard-cowl",
    kind: "badge",
    title: "Wizard Cowl",
    description: "Arcane hood crest for spell-casting learners.",
    priceGems: 130,
    tier: 3,
    emoji: "🧙",
    accent: "#6366f1",
  },
  {
    id: "badge-laurel-champion",
    kind: "badge",
    title: "Laurel Champion",
    description: "Victory wreath for multi-week streak heroes.",
    priceGems: 145,
    tier: 4,
    emoji: "🥇",
    accent: "#84cc16",
  },
  {
    id: "badge-ring-of-quest",
    kind: "badge",
    title: "Ring of Quest",
    description: "Golden band earned by daily quest finishers.",
    priceGems: 98,
    tier: 3,
    emoji: "💍",
    accent: "#f59e0b",
  },
  {
    id: "bundle-gems-small",
    kind: "gem_bundle",
    title: "Gem pouch",
    description: "Trade XP for a small gem top-up.",
    priceGems: 0,
    priceXp: 120,
    gemsGranted: 25,
    tier: 1,
    emoji: "🎒",
    accent: "#58cc02",
  },
  {
    id: "bundle-gems-medium",
    kind: "gem_bundle",
    title: "Gem satchel",
    description: "Better value exchange for active learners.",
    priceGems: 0,
    priceXp: 280,
    gemsGranted: 75,
    tier: 2,
    emoji: "💼",
    accent: "#1cb0f6",
    featured: true,
  },
  {
    id: "bundle-gems-large",
    kind: "gem_bundle",
    title: "Gem vault",
    description: "Big gem bundle for long study sessions.",
    priceGems: 0,
    priceXp: 500,
    gemsGranted: 150,
    tier: 3,
    emoji: "🏦",
    accent: "#7c3aed",
  },
  {
    id: "boost-streak-shield",
    kind: "boost",
    title: "Streak shield",
    description: "Protects your daily streak once (demo perk).",
    priceGems: 65,
    tier: 2,
    emoji: "🛡️",
    accent: "#6366f1",
  },
  {
    id: "boost-xp-rush",
    kind: "boost",
    title: "XP rush",
    description: "Marks a 24h XP boost flag on your profile.",
    priceGems: 85,
    tier: 3,
    emoji: "⚡",
    accent: "#ff9600",
  },
  {
    id: "bundle-gems-royal",
    kind: "gem_bundle",
    title: "Royal gem chest",
    description: "Premium XP exchange for serious collectors.",
    priceGems: 0,
    priceXp: 800,
    gemsGranted: 250,
    tier: 4,
    emoji: "👑",
    accent: "#ca8a04",
    featured: true,
  },
  {
    id: "boost-gem-magnet",
    kind: "boost",
    title: "Gem magnet",
    description: "Highlights gem rewards on your next quest claims.",
    priceGems: 95,
    tier: 3,
    emoji: "🧲",
    accent: "#06b6d4",
  },
  {
    id: "boost-owl-wisdom",
    kind: "boost",
    title: "Owl wisdom",
    description: "Night study boost — extra hint tokens (demo).",
    priceGems: 125,
    tier: 4,
    emoji: "🦉",
    accent: "#a16207",
  },
  {
    id: "boost-flame-ward",
    kind: "boost",
    title: "Flame ward",
    description: "Protects streak twice before expiring (demo).",
    priceGems: 110,
    tier: 3,
    emoji: "🔥",
    accent: "#f97316",
  },
];

export const SHOP_KIND_LABELS: Record<ShopItemKind, string> = {
  badge: "Badge",
  gem_bundle: "Gem bundle",
  boost: "Boost",
};

export function getShopItem(id: string): ShopCatalogItem | undefined {
  return SHOP_CATALOG.find((item) => item.id === id);
}
